# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wROoDK6Kjh4C8TD3LmFO7YY29EB7QDPt
"""

import pandas as pd

import numpy as np

import seaborn as sns

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

from sklearn.preprocessing import LabelEncoder

from sklearn.metrics import mean_squared_error, r2_score



from google.colab import files

uploaded = files.upload()

df = pd.read_csv('IMDb Movies India.csv', encoding='ISO-8859-1')

print("First 5 rows:\n", df.head())

print("\nDataset Info:\n")

print(df.info())

print("\nMissing Values:\n", df.isnull().sum())

df = df[['Genre', 'Director', 'Actor 1', 'Actor 2', 'Actor 3', 'Rating']]

df.dropna(inplace=True)

label_encoders = {}
for col in ['Genre', 'Director', 'Actor 1', 'Actor 2', 'Actor 3']:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

X = df.drop('Rating', axis=1)

y = df['Rating']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print( mean_squared_error(y_test, y_pred))

print( r2_score(y_test, y_pred))

results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})

print("\nSample Predictions:\n", results.head())

plt.scatter(y_test, y_pred, alpha=0.5)

plt.xlabel("Actual Ratings")

plt.ylabel("Predicted Ratings")

plt.title("Actual vs Predicted Ratings")

plt.show()